#' @importFrom stats dnbinom predict
#' @importFrom ggplot2 ggplot geom_point scale_colour_gradient2 xlab ylab aes
.plotDmmScatter <- function(model, log=TRUE, pointsize=1.2) {

  # Regression mixture model
  if (all(c("fit1", "fit2", "pi") %in% names(model))) {
    mu1 <- predict(model$fit1, type="response")
    mu2 <- predict(model$fit2, type="response")
    theta1 <- model$fit1$theta
    theta2 <- model$fit2$theta
    f <- matrix(nrow=length(mu1), ncol=2)
    f[, 1] <- dnbinom(model$fit1$y, mu=mu1, size=theta1)
    f[, 2] <- dnbinom(model$fit2$y, mu=mu2, size=theta2)
    pi.f <- t(model$pi * t(f))
    posteriorProb <- pi.f / apply(pi.f, 1, sum)

    rna <- exp(model$fit1$model$rna)
    hto <- model$fit1$y
  
  # Naive regression model not implemented
  } else {
    stop("Parameter model must be a regression mixture model generated by demuxmix().")
  }
  
  if (log) {
    df <- data.frame(hto=log10(hto+1), rna=log10(rna+1), posteriorProb=posteriorProb[, 2])
    xlab <- expression('log'[10]*'(HTO count)')
    ylab <- expression('log'[10]*'(RNA features detected)')
  } else {
    df <- data.frame(hto=hto, rna=rna, posteriorProb=posteriorProb[, 2])
    xlab <- "HTO count"
    ylab <- "RNA features detected"
  }
  
  p <- ggplot(df, aes(x=hto, y=rna, color=posteriorProb)) +
    geom_point(size=pointsize) +
    scale_colour_gradient2(name="Posterior\nprobability", low="dodgerblue", mid="black", high="firebrick2", midpoint=0.5) +
    xlab(xlab) +
    ylab(ylab)
  
  return(p)
}


#' @importFrom ggplot2 ggtitle
#' @importFrom gridExtra grid.arrange
setMethod("plotDmmScatter", signature=c(model="list"),
  function (model, log=TRUE, pointsize=1.2) {
    # Only one model given (for one hashtag)
    if (all(c("mu1", "mu2", "theta1", "theta2", "pi") %in% names(model)) | all(c("fit1", "fit2", "pi") %in% names(model))) {
      return(.plotDmmScatter(model, log=log, pointsize=pointsize))
              
    # List of models for multiple hashtags
    } else if (length(model) == 1) {
      return(.plotDmmScatter(model[[1]], log=log, pointsize=pointsize))
    } else {
      plots <- lapply(model, .plotDmmScatter, log=log, pointsize=pointsize)
      for (i in 1:length(plots)) {
        plots[[i]] <- plots[[i]] + ggtitle(names(plots)[i])
      }
      return(do.call(grid.arrange, plots))
    }
  }
)